title: RL Project
author: Agastya Agrawal
copyright: "2026 Agastya Agrawal"
execute:
  execute_notebooks: off 

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/AgastyaAgrawal/RL1
  path_to_book: .
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"